### ISSUE TITLE
License Missing

### ISSUE THREAD

**Issue by swalahamani** [shawnalexsony/Business_Card_PCB#1]
Hi @shawnalexsony 👋

This is really amazing work 🎉 Thanks for publishing it 🙏

Could you please add a license?

**Comment by shawnalexsony** [comment]
Hi @swalahamani 

Thanks for the heads-up, 

I've added <b>GNU General Public License v3.0</b> for this project.

Regards,
Shawn

**Comment by swalahamani** [comment]
Thanks @shawnalexsony
